### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by buaaswf** [KaihuaTang/Scene-Graph-Benchmark.pytorch#110]
/data/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:322:1: note: declared here
   T * data() const {
 ^ ~~
/data/swfcode/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.cu:855:106: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated [-Wdeprecated-declarations]
         const scalar_t *data_col_ = data_col.data<scalar_t>();
                                                                                                          ^
/data/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:322:1: note: declared here
   T * data() const {
 ^ ~~
ninja: build stopped: subcommand failed.
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: 
No module named 'torchvision'
Traceback (most recent call last):
  File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/swf/anaconda3/envs/scene_graph_benchmark/bin/python', '-u', 'tools/relation_train_net.py', '--local_rank=1', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'True', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'True', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'MotifPredictor', 'SOLVER,IMS_PER_BATCH', '12', 'TEST.IMS_PER_BATCH', '2', 'DTYPE', 'float16', 'SOLVER.MAX_ITER', '50000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'GLOVE_DIR', '/home/swf/glove', 'MODEL.PRETRAINED_DETECTOR_CKPT', '/home/swf/checkpoints/pretrained_faster_rcnn/model_final.pth', 'OUTPUT_DIR', '/home/swf/checkpoints.motif-precls-exmp']' returned non-zero exit status 1.

**Comment by waxnkw** [comment]
> /data/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:322:1: note: declared here
> T * data() const {
> ^ ~~
> /data/swfcode/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.cu:855:106: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated [-Wdeprecated-declarations]
> const scalar_t *data_col_ = data_col.data<scalar_t>();
> ^
> /data/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:322:1: note: declared here
> T * data() const {
> ^ ~~
> ninja: build stopped: subcommand failed.
> raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError:
> No module named 'torchvision'
> Traceback (most recent call last):
> File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 87, in _run_code
> exec(code, run_globals)
> File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in
> main()
> File "/home/swf/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
> raise subprocess.CalledProcessError(returncode=process.returncode,
> subprocess.CalledProcessError: Command '['/home/swf/anaconda3/envs/scene_graph_benchmark/bin/python', '-u', 'tools/relation_train_net.py', '--local_rank=1', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'True', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'True', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'MotifPredictor', 'SOLVER,IMS_PER_BATCH', '12', 'TEST.IMS_PER_BATCH', '2', 'DTYPE', 'float16', 'SOLVER.MAX_ITER', '50000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'GLOVE_DIR', '/home/swf/glove', 'MODEL.PRETRAINED_DETECTOR_CKPT', '/home/swf/checkpoints/pretrained_faster_rcnn/model_final.pth', 'OUTPUT_DIR', '/home/swf/checkpoints.motif-precls-exmp']' returned non-zero exit status 1.

Does it means you need to install  torchvision?
