### ISSUE TITLE
Running on custom images

### ISSUE THREAD

**Issue by farahFif** [KaihuaTang/Scene-Graph-Benchmark.pytorch#189]
Hi, 

I am trying to run on custom image. However I got this error it seems like the checkpoint loaded doesn't match with current model. Moreover I get this weird error that cfg.DATASETS has no attribute TO_TEST. Can you help @KaihuaTang 

```
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.2.running_mean of shape (128,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.2.running_var of shape (128,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.2.weight of shape (128,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.4.bias of shape (256,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.4.weight of shape (256, 128, 3, 3)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.6.bias of shape (256,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.6.num_batches_tracked of shape ()
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.6.running_mean of shape (256,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.6.running_var of shape (256,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: roi_heads.relation.union_feature_extractor.rect_conv.6.weight of shape (256,)
2023-01-26 08:11:17,985 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.anchor_generator.cell_anchors.0 of shape (4, 4)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.anchor_generator.cell_anchors.1 of shape (4, 4)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.anchor_generator.cell_anchors.2 of shape (4, 4)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.anchor_generator.cell_anchors.3 of shape (4, 4)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.anchor_generator.cell_anchors.4 of shape (4, 4)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.bbox_pred.bias of shape (16,)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.bbox_pred.weight of shape (16, 256, 1, 1)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.cls_logits.bias of shape (4,)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.cls_logits.weight of shape (4, 256, 1, 1)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.conv.bias of shape (256,)
2023-01-26 08:11:17,986 maskrcnn_benchmark.utils.model_serialization INFO: NO-MATCHING of current module: rpn.head.conv.weight of shape (256, 256, 3, 3)
Traceback (most recent call last):
  File "tools/relation_test_net.py", line 126, in <module>
    main()
  File "tools/relation_test_net.py", line 95, in main
    if cfg.DATASETS.TO_TEST:
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TO_TEST
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2102774) of binary: /storage/miniconda3/envs/myvenv/bin/python
Traceback (most recent call last):
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/storage/miniconda3/envs/myvenv/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

```

**Comment by MeinhardMark** [comment]
how did you solve this problem?
