### ISSUE TITLE
SGDet on Custom Images

### ISSUE THREAD

**Issue by 1286169349** [KaihuaTang/Scene-Graph-Benchmark.pytorch#202]
## ❓ Questions and Help
Traceback (most recent call last):
  File "tools/relation_test_net.py", line 123, in <module>
    main()
  File "tools/relation_test_net.py", line 105, in main
    data_loaders_val = make_data_loader(cfg=cfg, mode="test", is_distributed=distributed, dataset_to_test=cfg.DATASETS.TO_TEST)
  File "/home/zzu_zxw/zjl_data/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/build.py", line 227, in make_data_loader
    datasets = build_dataset(cfg, dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/zzu_zxw/zjl_data/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/build.py", line 103, in build_dataset
    dataset = factory(**args)
  File "/home/zzu_zxw/zjl_data/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 52, in __init__
    self.ind_to_classes, self.ind_to_predicates, self.ind_to_attributes = load_info(dict_file) # contiguous 151, 51 containing __background__
  File "/home/zzu_zxw/zjl_data/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 276, in load_info
    info = json.load(open(dict_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/media/rafi/Samsung_T5/_DATASETS/vg/VG-SGG-dicts-with-attri.json'

**Comment by devanshrj** [comment]
Hi, thanks for this awesome work! I am also running into the same error on using SGDet on custom images. Were you able to resolve this?

**Comment by Drome586** [comment]
Hi, I had the same problem, may I ask how you finally solved it?

**Comment by narchitect** [comment]
you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py

**Comment by Drome586** [comment]
> you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py

Thank you, my brother.

**Comment by Drome586** [comment]
> you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py

I also have a small question I'd like to ask.Recently I had an idea to try and introduce a "Tree" structure into the Transformer, but I'm at a loss? Do you have any insights?

**Comment by Maelic** [comment]
> > you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py
> 
> I also have a small question I'd like to ask.Recently I had an idea to try and introduce a "Tree" structure into the Transformer, but I'm at a loss? Do you have any insights?

Hi @Drome586 ,

You may have a look at [this](https://github.com/CYVincent/Scene-Graph-Transformer-CogTree), [this](https://github.com/Kenneth-Wong/het-eccv20) and [this](https://github.com/KaihuaTang/VCTree-Scene-Graph-Generation) (this last implementation is also part of this codebase [here](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/4b6b71a90d4198d9dae574d42b062a5e534da291/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_vctree.py)).

**Comment by Drome586** [comment]
Thank you very much for your reply and I wish you all the best!
















At 2024-02-15 01:36:37, "Maëlic Neau" ***@***.***> wrote:

you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py

I also have a small question I'd like to ask.Recently I had an idea to try and introduce a "Tree" structure into the Transformer, but I'm at a loss? Do you have any insights?

Hi @Drome586 ,

You may have a look at this, this and this (this last implementation is also part of this codebase here).

**Comment by majianbo3** [comment]
> Thank you very much for your reply and I wish you all the best! At 2024-02-15 01:36:37, "Maëlic Neau" ***@***.***> wrote: you need to change the default path for the dataset from ../maskrcnn_benchmark/config/paths_catalog.py I also have a small question I'd like to ask.Recently I had an idea to try and introduce a "Tree" structure into the Transformer, but I'm at a loss? Do you have any insights? Hi @Drome586 , You may have a look at this, this and this (this last implementation is also part of this codebase here). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>
> 
> 非常感谢您的回复，祝您一切顺利！ 2024-02-15 01：36：37，“Maëlic Neau”*@*.*& gt; wrote： 您需要将数据集的默认路径从../ maskrcnn_benchmark/config/paths_catalog.py 我还有一个小问题想问，最近我有一个想法，想尝试在Transformer中引入一个“树”结构，但我不知所措？你有什么见解吗？ 嗨@Drome586， 你可以看看这个，这个和这个（最后一个实现也是这个代码库的一部分）。 - 直接回复此电子邮件，在GitHub上查看或取消订阅。 您收到此消息是因为有人提到您。消息ID：*@*.*& gt;

Hello, I have been customizing my own dataset recently. If you could share your work with me, I would greatly appreciate it
