### ISSUE TITLE
issues when testing on images without anotations

### ISSUE THREAD

**Issue by joey-wang123** [KaihuaTang/Scene-Graph-Benchmark.pytorch#46]
## ❓ Questions and Help
Hello,

        Thanks for your great work! Recently, I am using your code and pre-trained model for scene graph generation on other images but without ground truth annotations, and for the code in 

```
x, result, detector_losses '= self.roi_heads(features, proposals, targets, logger)
```

and 

```
    def assign_label_to_proposals(self, proposals, targets):
        for img_idx, (target, proposal) in enumerate(zip(targets, proposals)):
            match_quality_matrix = boxlist_iou(target, proposal)
            matched_idxs = self.proposal_matcher(match_quality_matrix)
            # Fast RCNN only need "labels" field for selecting the targets
            target = target.copy_with_fields(["labels", "attributes"])
            matched_targets = target[matched_idxs.clamp(min=0)]
            
            labels_per_image = matched_targets.get_field("labels").to(dtype=torch.int64)
            attris_per_image = matched_targets.get_field("attributes").to(dtype=torch.int64)

            labels_per_image[matched_idxs < 0] = 0
            attris_per_image[matched_idxs < 0, :] = 0
            proposals[img_idx].add_field("labels", labels_per_image)
            proposals[img_idx].add_field("attributes", attris_per_image)
        return proposals
```
They all require targets, when I pass the
```
targets = None
```
There will be the following errors:

```
Traceback (most recent call last):
  File "tools/relation_test_net.py", line 113, in <module>
    main()
  File "tools/relation_test_net.py", line 97, in main
    inference(
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/engine/inference.py", line 146, in inference
    predictions = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=inference_timer)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/engine/inference.py", line 39, in compute_on_dataset
    output = model(images.to(device), targets)
  File "anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 53, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 27, in forward
    x, detections, loss_box = self.box(features, proposals, targets)
  File "anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 67, in forward
    proposals = self.samp_processor.assign_label_to_proposals(proposals, targets)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/sampling.py", line 119, in assign_label_to_proposals
    for img_idx, (target, proposal) in enumerate(zip(targets, proposals)):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
```

Is this a bug, since when testing on other images, targets information is not necessary, right? 
Thank you for your help!

**Comment by KaihuaTang** [comment]
Although the target information is not used, I could redundantly conduct some processing during testing, e.g., the label information is not used in the testing, but the pre-processing self.samp_processor.assign_label_to_proposals(proposals, targets) is not removed. 
Maybe change it to:
if self.training:
      self.samp_processor.assign_label_to_proposals(proposals, targets)
could solve your problem.

**Comment by joey-wang123** [comment]
```
x, result = self.post_processor((x, class_logits, box_regression), proposals, relation_mode=True)
  File "/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 97, in forward
    boxlist = self.add_important_fields(i, boxes, orig_inds, boxlist, boxes_per_cls, relation_mode)
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 107, in add_important_fields
    gt_labels = boxes[i].get_field('labels')[orig_inds]
  File "/scenegraph/Scene-Graph-Benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 48, in get_field
    return self.extra_fields[field]
KeyError: 'labels'
```
After chaning the code, it has above error,  looks like the label information is used.

**Comment by KaihuaTang** [comment]
I see. Since in PredCls setting, object label is used for both training and testing, so my current code will always prepare the label information, although in SGDet the object label is not used in testing. 
I think I will add a new switch to allow SGDet on custom images later.

**Comment by nyj-ocean** [comment]
@KaihuaTang 
Thanks for your work!

I notice that you had added `SGDet on Custom Images`

I want to know how to visualize the  Custom Images

Since `2.visualize_SGDet.ipynb` need `eval_results.pytorch`  and `visual_info.json`

But there is only `custom_prediction.pytorch`

**Comment by Opdoop** [comment]
@nyj-ocean Have you solved the problem? I also only get `custom_prediction.pytorch` using `SGDet on Custom Images`. 
And another question is `torch.load('custom_prediction.pytorch')` return a list of `BoxList`, how to know which picture is map to which `BoxList`?

**Comment by KaihuaTang** [comment]
> @nyj-ocean Have you solved the problem? I also only get `custom_prediction.pytorch` using `SGDet on Custom Images`.
> And another question is `torch.load('custom_prediction.pytorch')` return a list of `BoxList`, how to know which picture is map to which `BoxList`?

I change the Scene Graph Detection on Custom Images to output a json file and even support the visualization. Please check the recent updates.
