### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by nullkatar** [KaihuaTang/Scene-Graph-Benchmark.pytorch#52]
## ❓ Questions and Help
Hello! I am facing the following issue: 

```
  File "tools/detector_pretrain_net.py", line 315, in <module>
    main()
  File "tools/detector_pretrain_net.py", line 308, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/detector_pretrain_net.py", line 72, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT, update_schedule=cfg.SOLVER.UPDATE_SCHEDULE_DURING_LOAD)
  File "/home/lkochiev/Documents/SFU/NSM/SGB/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 65, in load
    self._load_model(checkpoint, load_mapping)
  File "/home/lkochiev/Documents/SFU/NSM/SGB/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 106, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), load_mapping)
  File "/home/lkochiev/Documents/SFU/NSM/SGB/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/model_serialization.py", line 94, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/lkochiev/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 829, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
        size mismatch for roi_heads.box.feature_extractor.fc7.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([2048, 4096]).
        size mismatch for roi_heads.box.feature_extractor.fc7.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([151, 4096]) from checkpoint, the shape in current model is torch.Size([151, 2048]).
        size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([604, 4096]) from checkpoint, the shape in current model is torch.Size([604, 2048]).
Traceback (most recent call last):
  File "/home/lkochiev/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lkochiev/anaconda3/envs/scene_graph_benchmark/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lkochiev/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/lkochiev/anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
```
while running the follwoing command:

`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 10001 --nproc_per_node=1 tools/detector_pretrain_net.py --config-file "configs/e2e_relation_detector_X_101_32_8_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 6 TEST.IMS_PER_BATCH 1 DTYPE "float16" SOLVER.MAX_ITER 50000 SOLVER.STEPS "(30000, 45000)" SOLVER.VAL_PERIOD 2000 SOLVER.CHECKPOINT_PERIOD 2000 MODEL.RELATION_ON True MODEL.ATTRIBUTE_ON True OUTPUT_DIR /home/lkochiev/checkpoints/pretrained_faster_rcnn SOLVER.PRE_VAL False`

Can I ask you how can I eliminate it?

**Comment by nullkatar** [comment]
Well, just in case I manaully cropped all weigts and momentum tensors as well, Yep it lowers the performance but I don't see any other solution to this....
