### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Cathy-t** [KaihuaTang/Scene-Graph-Benchmark.pytorch#66]
## ❓ Questions and Help
when I run 'SGDet on Custom Images' , the following error is reported.

Traceback (most recent call last):
  File "tools/relation_test_net.py", line 11, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader, get_dataset_statistics
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/data/build.py", line 12, in <module>
    from maskrcnn_benchmark.utils.miscellaneous import save_labels
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/utils/miscellaneous.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/structures/boxlist_ops.py", line 7, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/venv/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/media/cat/f30f0201-cf51-4278-afbf-5650c2857e7b/C-/pycharmPro/Scene-Graph-Benchmark.pytorch-master/venv/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)

Can you help me ?

**Comment by KaihuaTang** [comment]
It looks like you didn't build the project correctly.
please check https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/issues/60

**Comment by Cathy-t** [comment]
I reconfigured the environment and it worked.Thank  you!
