### ISSUE TITLE
Problem of 'TEST.IMS_PER_BATCH'

### ISSUE THREAD

**Issue by liuhl-source** [KaihuaTang/Scene-Graph-Benchmark.pytorch#76]
When testing on custom images, I change the 'TEST.IMS_PER_BATCH' to 4 with 4 gpu available.But I got this assertion:
`  File "..../Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py", line 178, in forward
    assert l_batch == 1
AssertionError
`

There are some constrains in your code, can i testing the custom images with multiple gpus?  Hope to get some guidance, thank you!

**Comment by KaihuaTang** [comment]
Some assertions are inherited from https://github.com/rowanz/neural-motifs , because I used his post-precessing, but actually I reimplemented most part of the codes, so removing it may not cause any problem (I'm not sure). You can try removing it and see what's going on. 
Sorry that I'm working on another project, so I don't have additional GPUs to test it.

**Comment by KaihuaTang** [comment]
If the result looks fine and no bug occurs after removing this assertion (assert l_batch == 1), please tell me, so I can remove it from the master branch.

**Comment by liuhl-source** [comment]
> Some assertions are inherited from https://github.com/rowanz/neural-motifs , because I used his post-precessing, but actually I reimplemented most part of the codes, so removing it may not cause any problem (I'm not sure). You can try removing it and see what's going on.
> Sorry that I'm working on another project, so I don't have additional GPUs to test it.
`Traceback (most recent call last):
  File "tools/relation_test_net.py", line 113, in <module>
    main()
  File "tools/relation_test_net.py", line 97, in main
    inference(
  File "/home/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/engine/inference.py", line 110, in inference
    predictions = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=inference_timer)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/engine/inference.py", line 34, in compute_on_dataset
    output = model(images.to(device), targets)
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 69, in forward
    x, detections, loss_relation = self.relation(features, detections, targets, logger)
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 80, in forward
    refine_logits, relation_logits, add_losses = self.predictor(proposals, rel_pair_idxs, rel_labels, rel_binarys, roi_features, union_features, logger)
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py", line 574, in forward
    post_ctx_rep, pair_pred, pair_bbox, pair_obj_probs, binary_preds, obj_dist_prob, edge_rep, obj_dist_list = self.pair_feature_generate(roi_features, proposals, rel_pair_idxs, num_objs, obj_boxs, logger)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py", line 521, in pair_feature_generate
    obj_dists, obj_preds, edge_ctx, binary_preds = self.context_layer(roi_features, proposals, rel_pair_idxs, logger, ctx_average=ctx_average)
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py", line 382, in forward
    obj_dists, obj_preds, obj_ctx, perm, inv_perm, ls_transposed = self.obj_ctx(obj_pre_rep, proposals, obj_labels, boxes_per_cls, ctx_average=ctx_average)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py", line 321, in obj_ctx
    obj_dists, obj_preds = self.decoder_rnn(
  File "/home//anaconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py", line 197, in forward
    out_commitments[int(box_ind)] = int(cls_ind)
IndexError: index 88 is out of bounds for dimension 0 with size 80`

Thanks for your reply! Actually it cause a new problem. I am not familiar with your code. Can you find any clues of this bug?

**Comment by liuhl-source** [comment]
<img width="1273" alt="图片" src="https://user-images.githubusercontent.com/25958403/90379406-48966000-e0ad-11ea-9687-48cb0ca6f524.png">
Thanks for your reply! actually it cause a new problem. I'm not familiar with your code, can you find any solution? thank you!

**Comment by KaihuaTang** [comment]
The error comes from the post-processing I inherited from motifs. I think the assertion is necessary. TEST.IMS_PER_BATCH == num of GPUs should be fine. I'm not sure why you trigger the assertion in the first place.

**Comment by liuhl-source** [comment]
> The error comes from the post-processing I inherited from motifs. I think the assertion is necessary. TEST.IMS_PER_BATCH == num of GPUs should be fine. I'm not sure why you trigger the assertion in the first place.

Thanks for your reply, but I have tried this setting, same issue with the AssertionError.  I just set 'CUDA_VISIBLE_DEVICES=2,3,4,5' and 'TEST.IMS_PER_BATCH = 4'.
