### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by vrdn-23** [KaihuaTang/Scene-Graph-Benchmark.pytorch#98]
## ❓ Questions and Help
I'm getting this error when trying to train the model in a custom dataset. Could you please let me know if this is something that has a fix, or something that you're aware of?

```python
2020-11-03 00:07:32,206 maskrcnn_benchmark INFO: Validate before training
  0%|
            | 0/2 [00:00<?, ?it/s]2020-11-03 00:07:32,254 maskrcnn_benchmark INFO: Start evaluation on vinay_val dataset(4 images).
  0%|
            | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/sg/tools/relation_train_net.py", line 379, in <module>
    main()
  File "/sg/tools/relation_train_net.py", line 372, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "/sg/tools/relation_train_net.py", line 124, in train
    run_val(cfg, model, val_data_loaders, distributed, logger)
  File "/sg/tools/relation_train_net.py", line 259, in run_val
    logger=logger,
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/engine/inference.py", line 110, in inference
    predictions = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=inference_timer)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/engine/inference.py", line 34, in compute_on_dataset
    output = model(images.to(device), targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 69, in forward
    x, detections, loss_relation = self.relation(features, detections, targets, logger)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 74, in forward
    union_features = self.union_feature_extractor(features, proposals, rel_pair_idxs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 90, in forward
    rect_features = self.rect_conv(rect_inputs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
  0%|
            | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/sg/tools/relation_train_net.py", line 379, in <module>
    main()
  File "/sg/tools/relation_train_net.py", line 372, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "/sg/tools/relation_train_net.py", line 124, in train
    run_val(cfg, model, val_data_loaders, distributed, logger)
  File "/sg/tools/relation_train_net.py", line 259, in run_val
    logger=logger,
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/engine/inference.py", line 110, in inference
    predictions = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=inference_timer)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/engine/inference.py", line 34, in compute_on_dataset
    output = model(images.to(device), targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 69, in forward
  x, detections, loss_relation = self.relation(features, detections, targets, logger)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 74, in forward
    union_features = self.union_feature_extractor(features, proposals, rel_pair_idxs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 93, in forward
    union_vis_features = self.feature_extractor.pooler(x, union_proposals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/modeling/poolers.py", line 134, in forward
    result = self.reduce_channel(result.contiguous())
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/src/nvidia-418.87.01/sg_docker/maskrcnn_benchmark/layers/misc.py", line 33, in forward
    return super(Conv2d, self).forward(x)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/miniconda/envs/py36/bin/python', '-u', '/sg/tools/relation_train_net.py', '--local_rank=1', '--config-file', '/sg/configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX
', 'False', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'False', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'CausalAnalysisPredictor', 'MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE', 'none', 'MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE', 'sum',
 'MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER', 'motifs', 'SOLVER.IMS_PER_BATCH', '12', 'TEST.IMS_PER_BATCH', '2', 'DTYPE', 'float16', 'SOLVER.MAX_ITER', '50000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'GLOVE_DI
R', '/glove', 'OUTPUT_DIR', '/results/TransformerTraining']' returned non-zero exit status 1.`
```
I am using all the versions as specified by the INSTALL.MD. The error is reproducible on my local which uses CUDA 11.0 and also on a docker container which uses CUDA 10.1. I've tried setting up for both environments but to no avail. 

Any help you can give would be highly appreciated. Please let me know if you require any other info.

**Comment by vrdn-23** [comment]
I only get this issue when I run inference/validation. Training seems to happen fine. Any idea why this might be an issue?

**Comment by vrdn-23** [comment]
Closing cause I'm no longer working on this and I don't remember what I did to fix it!
